# Initial Configuration for docker compose in production env with Postgresql support
# WiP 
# Written by poppopjmp
networks:
  spiderfoot_808:
    external: true 
services:
  spiderfoot.local:
    networks:
      spiderfoot_808:
        ipv4_address: 172.24.0.42  # Static IP for SpiderFoot
    volumes:
      - spiderfoot-data:/var/lib/spiderfoot
      - spiderfoot-logs:/home/spiderfoot/.spiderfoot/logs
      - spiderfoot-cache:/var/lib/spiderfoot/cache
    image: 808spiderfoot:latest
    container_name: 808spiderfoot
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=spiderfoot
      - POSTGRES_USER=spiderfoot
      - POSTGRES_PASSWORD=v8086942069!!
    extra_hosts:
      - "mytor.local:172.24.0.1" 

  postgres.local:
    image: postgres:latest
    networks:
      spiderfoot_808:
        ipv4_address: 172.24.0.69 
    container_name: postgres
    environment:
      - POSTGRES_DB=spiderfoot
      - POSTGRES_USER=spiderfoot
      - POSTGRES_PASSWORD=v8086942069!!
    extra_hosts:
      - "mytor.local:172.24.0.1" 
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
### Generate Certificate with generate-certificate script that will populate certs folder with the key
### If you have you own CA generate from there and populate accordingly

  nginx.local:  # Add Nginx service
    networks:
      spiderfoot_808:
        ipv4_address: 172.24.0.80
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"  # Expose port 80 on the host
      - "80:80"
    volumes:
      - ./docker-compose-production-files/nginx.conf:/etc/nginx/nginx.conf:ro 
      - ./docker-compose-production-files/certs:/etc/nginx/certs:ro 
    depends_on:  # Ensure Nginx starts after SpiderFoot
      - spiderfoot.local
    extra_hosts:
      - "mytor.local:172.24.0.1"  # Corrected entry for mytor.local
    restart: unless-stopped


volumes:
  spiderfoot-data:
    name: spiderfoot-data
  spiderfoot-logs:
    name: spiderfoot-logs
  spiderfoot-cache:
    name: spiderfoot-cache
  postgres-data:
    name: postgres-data
  certs:
    name: certs