// ...existing code...
raise SyntaxError(f"Error loading module {modName}: {e}") from e  # Fix exception chaining
// ...existing code...
# Remove the blank line containing whitespace
// ...existing code...
# Remove the blank line containing whitespace
// ...existing code...
