"""Backward-compatibility shim for constants.py.

This module re-exports from config/constants.py for backward compatibility.
"""

from __future__ import annotations

from .config.constants import (
    DEFAULT_TTL_ONE_HOUR,
    MODULE_TIMEOUT_SECONDS,
    SHORT_CACHE_TTL_SECONDS,
    SESSION_IDLE_TIMEOUT,
    DEFAULT_RESULT_LIMIT,
    DEFAULT_BATCH_SIZE,
    DEFAULT_MAX_RETRIES,
    DB_RETRY_BACKOFF_BASE,
    DEFAULT_API_PORT,
    DEFAULT_WEB_PORT,
    DEFAULT_VECTOR_PORT,
    MAX_BODY_BYTES,
    DEFAULT_MAX_TOKENS,
    DEFAULT_OPENAI_BASE_URL,
    DEFAULT_OLLAMA_BASE_URL,
    DEFAULT_VLLM_BASE_URL,
    DEFAULT_DOH_URL,
    DEFAULT_DATABASE_NAME,
)

__all__ = [
    "DEFAULT_TTL_ONE_HOUR",
    "MODULE_TIMEOUT_SECONDS",
    "SHORT_CACHE_TTL_SECONDS",
    "SESSION_IDLE_TIMEOUT",
    "DEFAULT_RESULT_LIMIT",
    "DEFAULT_BATCH_SIZE",
    "DEFAULT_MAX_RETRIES",
    "DB_RETRY_BACKOFF_BASE",
    "DEFAULT_API_PORT",
    "DEFAULT_WEB_PORT",
    "DEFAULT_VECTOR_PORT",
    "MAX_BODY_BYTES",
    "DEFAULT_MAX_TOKENS",
    "DEFAULT_OPENAI_BASE_URL",
    "DEFAULT_OLLAMA_BASE_URL",
    "DEFAULT_VLLM_BASE_URL",
    "DEFAULT_DOH_URL",
    "DEFAULT_DATABASE_NAME",
]
