# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from spiderfoot import spiderfoot_pb2 as spiderfoot__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in spiderfoot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScanServiceStub:
    """============================================================================
    Scan Service — submit, control, and monitor scans
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitScan = channel.unary_unary(
                '/spiderfoot.v1.ScanService/SubmitScan',
                request_serializer=spiderfoot__pb2.SubmitScanRequest.SerializeToString,
                response_deserializer=spiderfoot__pb2.SubmitScanResponse.FromString,
                _registered_method=True)
        self.AbortScan = channel.unary_unary(
                '/spiderfoot.v1.ScanService/AbortScan',
                request_serializer=spiderfoot__pb2.ScanIdRequest.SerializeToString,
                response_deserializer=spiderfoot__pb2.ScanControlResponse.FromString,
                _registered_method=True)
        self.PauseScan = channel.unary_unary(
                '/spiderfoot.v1.ScanService/PauseScan',
                request_serializer=spiderfoot__pb2.ScanIdRequest.SerializeToString,
                response_deserializer=spiderfoot__pb2.ScanControlResponse.FromString,
                _registered_method=True)
        self.ResumeScan = channel.unary_unary(
                '/spiderfoot.v1.ScanService/ResumeScan',
                request_serializer=spiderfoot__pb2.ScanIdRequest.SerializeToString,
                response_deserializer=spiderfoot__pb2.ScanControlResponse.FromString,
                _registered_method=True)
        self.GetScanStatus = channel.unary_unary(
                '/spiderfoot.v1.ScanService/GetScanStatus',
                request_serializer=spiderfoot__pb2.ScanIdRequest.SerializeToString,
                response_deserializer=spiderfoot__pb2.ScanStatusResponse.FromString,
                _registered_method=True)
        self.ListScans = channel.unary_unary(
                '/spiderfoot.v1.ScanService/ListScans',
                request_serializer=spiderfoot__pb2.ListScansRequest.SerializeToString,
                response_deserializer=spiderfoot__pb2.ListScansResponse.FromString,
                _registered_method=True)
        self.StreamScanEvents = channel.unary_stream(
                '/spiderfoot.v1.ScanService/StreamScanEvents',
                request_serializer=spiderfoot__pb2.ScanIdRequest.SerializeToString,
                response_deserializer=spiderfoot__pb2.ScanEvent.FromString,
                _registered_method=True)


class ScanServiceServicer:
    """============================================================================
    Scan Service — submit, control, and monitor scans
    ============================================================================

    """

    def SubmitScan(self, request, context):
        """Submit a new scan request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortScan(self, request, context):
        """Abort a running scan
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseScan(self, request, context):
        """Pause a running scan
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeScan(self, request, context):
        """Resume a paused scan
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScanStatus(self, request, context):
        """Get status of a specific scan
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListScans(self, request, context):
        """List all scans (with optional filters)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamScanEvents(self, request, context):
        """Stream real-time scan events
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScanServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitScan': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitScan,
                    request_deserializer=spiderfoot__pb2.SubmitScanRequest.FromString,
                    response_serializer=spiderfoot__pb2.SubmitScanResponse.SerializeToString,
            ),
            'AbortScan': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortScan,
                    request_deserializer=spiderfoot__pb2.ScanIdRequest.FromString,
                    response_serializer=spiderfoot__pb2.ScanControlResponse.SerializeToString,
            ),
            'PauseScan': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseScan,
                    request_deserializer=spiderfoot__pb2.ScanIdRequest.FromString,
                    response_serializer=spiderfoot__pb2.ScanControlResponse.SerializeToString,
            ),
            'ResumeScan': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeScan,
                    request_deserializer=spiderfoot__pb2.ScanIdRequest.FromString,
                    response_serializer=spiderfoot__pb2.ScanControlResponse.SerializeToString,
            ),
            'GetScanStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScanStatus,
                    request_deserializer=spiderfoot__pb2.ScanIdRequest.FromString,
                    response_serializer=spiderfoot__pb2.ScanStatusResponse.SerializeToString,
            ),
            'ListScans': grpc.unary_unary_rpc_method_handler(
                    servicer.ListScans,
                    request_deserializer=spiderfoot__pb2.ListScansRequest.FromString,
                    response_serializer=spiderfoot__pb2.ListScansResponse.SerializeToString,
            ),
            'StreamScanEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamScanEvents,
                    request_deserializer=spiderfoot__pb2.ScanIdRequest.FromString,
                    response_serializer=spiderfoot__pb2.ScanEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spiderfoot.v1.ScanService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('spiderfoot.v1.ScanService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScanService:
    """============================================================================
    Scan Service — submit, control, and monitor scans
    ============================================================================

    """

    @staticmethod
    def SubmitScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spiderfoot.v1.ScanService/SubmitScan',
            spiderfoot__pb2.SubmitScanRequest.SerializeToString,
            spiderfoot__pb2.SubmitScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spiderfoot.v1.ScanService/AbortScan',
            spiderfoot__pb2.ScanIdRequest.SerializeToString,
            spiderfoot__pb2.ScanControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spiderfoot.v1.ScanService/PauseScan',
            spiderfoot__pb2.ScanIdRequest.SerializeToString,
            spiderfoot__pb2.ScanControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spiderfoot.v1.ScanService/ResumeScan',
            spiderfoot__pb2.ScanIdRequest.SerializeToString,
            spiderfoot__pb2.ScanControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScanStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spiderfoot.v1.ScanService/GetScanStatus',
            spiderfoot__pb2.ScanIdRequest.SerializeToString,
            spiderfoot__pb2.ScanStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListScans(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spiderfoot.v1.ScanService/ListScans',
            spiderfoot__pb2.ListScansRequest.SerializeToString,
            spiderfoot__pb2.ListScansResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamScanEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/spiderfoot.v1.ScanService/StreamScanEvents',
            spiderfoot__pb2.ScanIdRequest.SerializeToString,
            spiderfoot__pb2.ScanEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DataServiceStub:
    """============================================================================
    Data Service — CRUD operations for scan data
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateScan = channel.unary_unary(
                '/spiderfoot.v1.DataService/CreateScan',
                request_serializer=spiderfoot__pb2.CreateScanRequest.SerializeToString,
                response_deserializer=spiderfoot__pb2.CreateScanResponse.FromString,
                _registered_method=True)
        self.GetScan = channel.unary_unary(
                '/spiderfoot.v1.DataService/GetScan',
                request_serializer=spiderfoot__pb2.ScanIdRequest.SerializeToString,
                response_deserializer=spiderfoot__pb2.ScanRecord.FromString,
                _registered_method=True)
        self.ListScanInstances = channel.unary_unary(
                '/spiderfoot.v1.DataService/ListScanInstances',
                request_serializer=spiderfoot__pb2.ListScansRequest.SerializeToString,
                response_deserializer=spiderfoot__pb2.ListScanRecordsResponse.FromString,
                _registered_method=True)
        self.DeleteScan = channel.unary_unary(
                '/spiderfoot.v1.DataService/DeleteScan',
                request_serializer=spiderfoot__pb2.ScanIdRequest.SerializeToString,
                response_deserializer=spiderfoot__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.StoreEvent = channel.unary_unary(
                '/spiderfoot.v1.DataService/StoreEvent',
                request_serializer=spiderfoot__pb2.StoreEventRequest.SerializeToString,
                response_deserializer=spiderfoot__pb2.StoreEventResponse.FromString,
                _registered_method=True)
        self.GetEvents = channel.unary_unary(
                '/spiderfoot.v1.DataService/GetEvents',
                request_serializer=spiderfoot__pb2.GetEventsRequest.SerializeToString,
                response_deserializer=spiderfoot__pb2.GetEventsResponse.FromString,
                _registered_method=True)
        self.GetUniqueEventTypes = channel.unary_unary(
                '/spiderfoot.v1.DataService/GetUniqueEventTypes',
                request_serializer=spiderfoot__pb2.ScanIdRequest.SerializeToString,
                response_deserializer=spiderfoot__pb2.EventTypesResponse.FromString,
                _registered_method=True)
        self.LogScanEvent = channel.unary_unary(
                '/spiderfoot.v1.DataService/LogScanEvent',
                request_serializer=spiderfoot__pb2.LogEventRequest.SerializeToString,
                response_deserializer=spiderfoot__pb2.Empty.FromString,
                _registered_method=True)
        self.GetScanLogs = channel.unary_unary(
                '/spiderfoot.v1.DataService/GetScanLogs',
                request_serializer=spiderfoot__pb2.GetScanLogsRequest.SerializeToString,
                response_deserializer=spiderfoot__pb2.GetScanLogsResponse.FromString,
                _registered_method=True)
        self.SetConfig = channel.unary_unary(
                '/spiderfoot.v1.DataService/SetConfig',
                request_serializer=spiderfoot__pb2.SetConfigRequest.SerializeToString,
                response_deserializer=spiderfoot__pb2.Empty.FromString,
                _registered_method=True)
        self.GetConfig = channel.unary_unary(
                '/spiderfoot.v1.DataService/GetConfig',
                request_serializer=spiderfoot__pb2.GetConfigRequest.SerializeToString,
                response_deserializer=spiderfoot__pb2.GetConfigResponse.FromString,
                _registered_method=True)


class DataServiceServicer:
    """============================================================================
    Data Service — CRUD operations for scan data
    ============================================================================

    """

    def CreateScan(self, request, context):
        """Scan instance CRUD
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListScanInstances(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteScan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreEvent(self, request, context):
        """Event storage
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUniqueEventTypes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogScanEvent(self, request, context):
        """Scan logs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScanLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetConfig(self, request, context):
        """Configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateScan': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateScan,
                    request_deserializer=spiderfoot__pb2.CreateScanRequest.FromString,
                    response_serializer=spiderfoot__pb2.CreateScanResponse.SerializeToString,
            ),
            'GetScan': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScan,
                    request_deserializer=spiderfoot__pb2.ScanIdRequest.FromString,
                    response_serializer=spiderfoot__pb2.ScanRecord.SerializeToString,
            ),
            'ListScanInstances': grpc.unary_unary_rpc_method_handler(
                    servicer.ListScanInstances,
                    request_deserializer=spiderfoot__pb2.ListScansRequest.FromString,
                    response_serializer=spiderfoot__pb2.ListScanRecordsResponse.SerializeToString,
            ),
            'DeleteScan': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteScan,
                    request_deserializer=spiderfoot__pb2.ScanIdRequest.FromString,
                    response_serializer=spiderfoot__pb2.DeleteResponse.SerializeToString,
            ),
            'StoreEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreEvent,
                    request_deserializer=spiderfoot__pb2.StoreEventRequest.FromString,
                    response_serializer=spiderfoot__pb2.StoreEventResponse.SerializeToString,
            ),
            'GetEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvents,
                    request_deserializer=spiderfoot__pb2.GetEventsRequest.FromString,
                    response_serializer=spiderfoot__pb2.GetEventsResponse.SerializeToString,
            ),
            'GetUniqueEventTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUniqueEventTypes,
                    request_deserializer=spiderfoot__pb2.ScanIdRequest.FromString,
                    response_serializer=spiderfoot__pb2.EventTypesResponse.SerializeToString,
            ),
            'LogScanEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.LogScanEvent,
                    request_deserializer=spiderfoot__pb2.LogEventRequest.FromString,
                    response_serializer=spiderfoot__pb2.Empty.SerializeToString,
            ),
            'GetScanLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScanLogs,
                    request_deserializer=spiderfoot__pb2.GetScanLogsRequest.FromString,
                    response_serializer=spiderfoot__pb2.GetScanLogsResponse.SerializeToString,
            ),
            'SetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetConfig,
                    request_deserializer=spiderfoot__pb2.SetConfigRequest.FromString,
                    response_serializer=spiderfoot__pb2.Empty.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=spiderfoot__pb2.GetConfigRequest.FromString,
                    response_serializer=spiderfoot__pb2.GetConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spiderfoot.v1.DataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('spiderfoot.v1.DataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataService:
    """============================================================================
    Data Service — CRUD operations for scan data
    ============================================================================

    """

    @staticmethod
    def CreateScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spiderfoot.v1.DataService/CreateScan',
            spiderfoot__pb2.CreateScanRequest.SerializeToString,
            spiderfoot__pb2.CreateScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spiderfoot.v1.DataService/GetScan',
            spiderfoot__pb2.ScanIdRequest.SerializeToString,
            spiderfoot__pb2.ScanRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListScanInstances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spiderfoot.v1.DataService/ListScanInstances',
            spiderfoot__pb2.ListScansRequest.SerializeToString,
            spiderfoot__pb2.ListScanRecordsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spiderfoot.v1.DataService/DeleteScan',
            spiderfoot__pb2.ScanIdRequest.SerializeToString,
            spiderfoot__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spiderfoot.v1.DataService/StoreEvent',
            spiderfoot__pb2.StoreEventRequest.SerializeToString,
            spiderfoot__pb2.StoreEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spiderfoot.v1.DataService/GetEvents',
            spiderfoot__pb2.GetEventsRequest.SerializeToString,
            spiderfoot__pb2.GetEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUniqueEventTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spiderfoot.v1.DataService/GetUniqueEventTypes',
            spiderfoot__pb2.ScanIdRequest.SerializeToString,
            spiderfoot__pb2.EventTypesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LogScanEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spiderfoot.v1.DataService/LogScanEvent',
            spiderfoot__pb2.LogEventRequest.SerializeToString,
            spiderfoot__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScanLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spiderfoot.v1.DataService/GetScanLogs',
            spiderfoot__pb2.GetScanLogsRequest.SerializeToString,
            spiderfoot__pb2.GetScanLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spiderfoot.v1.DataService/SetConfig',
            spiderfoot__pb2.SetConfigRequest.SerializeToString,
            spiderfoot__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spiderfoot.v1.DataService/GetConfig',
            spiderfoot__pb2.GetConfigRequest.SerializeToString,
            spiderfoot__pb2.GetConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HealthServiceStub:
    """============================================================================
    Health Service — universal health check for all services
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/spiderfoot.v1.HealthService/Check',
                request_serializer=spiderfoot__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=spiderfoot__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.Watch = channel.unary_stream(
                '/spiderfoot.v1.HealthService/Watch',
                request_serializer=spiderfoot__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=spiderfoot__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class HealthServiceServicer:
    """============================================================================
    Health Service — universal health check for all services
    ============================================================================

    """

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Watch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=spiderfoot__pb2.HealthCheckRequest.FromString,
                    response_serializer=spiderfoot__pb2.HealthCheckResponse.SerializeToString,
            ),
            'Watch': grpc.unary_stream_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=spiderfoot__pb2.HealthCheckRequest.FromString,
                    response_serializer=spiderfoot__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spiderfoot.v1.HealthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('spiderfoot.v1.HealthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HealthService:
    """============================================================================
    Health Service — universal health check for all services
    ============================================================================

    """

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spiderfoot.v1.HealthService/Check',
            spiderfoot__pb2.HealthCheckRequest.SerializeToString,
            spiderfoot__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/spiderfoot.v1.HealthService/Watch',
            spiderfoot__pb2.HealthCheckRequest.SerializeToString,
            spiderfoot__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
