# -*- coding: utf-8 -*-
# =============================================================================
# SpiderFoot — PDF Renderer (WeasyPrint)
# =============================================================================
# Converts HTML reports to PDF with print-optimized styling.
# Integrates with the existing ReportFormatter HTML output path.
# =============================================================================

from __future__ import annotations

import io
import logging
import os
from dataclasses import dataclass, field
from typing import Any

log = logging.getLogger("spiderfoot.reporting.pdf_renderer")


@dataclass
class PDFBranding:
    """Branding configuration for PDF reports."""

    company_name: str = "SpiderFoot"
    logo_path: str | None = None
    primary_color: str = "#1a73e8"
    secondary_color: str = "#34a853"
    accent_color: str = "#ea4335"
    font_family: str = "Inter, Helvetica, Arial, sans-serif"
    header_text: str = ""
    footer_text: str = "Confidential — Generated by SpiderFoot"
    cover_subtitle: str = "Open Source Intelligence Report"

    @classmethod
    def from_env(cls) -> PDFBranding:
        """Build branding from environment variables."""
        return cls(
            company_name=os.environ.get("SF_REPORT_COMPANY", "SpiderFoot"),
            logo_path=os.environ.get("SF_REPORT_LOGO"),
            primary_color=os.environ.get("SF_REPORT_PRIMARY_COLOR", "#1a73e8"),
            footer_text=os.environ.get(
                "SF_REPORT_FOOTER", "Confidential — Generated by SpiderFoot"
            ),
        )


@dataclass
class PDFConfig:
    """Configuration for PDF rendering."""

    page_size: str = "A4"
    orientation: str = "portrait"
    margin_top: str = "25mm"
    margin_bottom: str = "25mm"
    margin_left: str = "20mm"
    margin_right: str = "20mm"
    include_cover_page: bool = True
    include_toc: bool = True
    include_page_numbers: bool = True
    include_header_footer: bool = True
    branding: PDFBranding = field(default_factory=PDFBranding)


class PDFRenderer:
    """Render HTML report content to PDF using WeasyPrint.

    Usage::

        from spiderfoot.reporting.pdf_renderer import PDFRenderer, PDFConfig
        from spiderfoot.reporting.report_formatter import ReportFormatter

        formatter = ReportFormatter()
        renderer = PDFRenderer()

        html_content = formatter.to_html(report)
        pdf_bytes = renderer.render(html_content, title="Scan Report")
    """

    def __init__(self, config: PDFConfig | None = None) -> None:
        self.config = config or PDFConfig()
        self._check_weasyprint()

    def _check_weasyprint(self) -> None:
        """Verify WeasyPrint is available."""
        try:
            import weasyprint  # noqa: F401

            self._available = True
        except ImportError:
            log.warning(
                "WeasyPrint not installed. PDF rendering unavailable. "
                "Install with: pip install weasyprint"
            )
            self._available = False

    @property
    def available(self) -> bool:
        return self._available

    def render(
        self,
        html_content: str,
        title: str = "SpiderFoot Report",
        metadata: dict[str, Any] | None = None,
    ) -> bytes:
        """Render HTML to PDF bytes.

        Args:
            html_content: The HTML report body.
            title: Document title for PDF metadata.
            metadata: Optional key-value metadata for the PDF document.

        Returns:
            PDF file content as bytes.

        Raises:
            RuntimeError: If WeasyPrint is not available.
        """
        if not self._available:
            raise RuntimeError(
                "WeasyPrint is not installed. Install with: pip install weasyprint"
            )

        import weasyprint
        from weasyprint import CSS

        # Build full HTML document with print styles
        full_html = self._build_full_document(html_content, title)

        # Create WeasyPrint HTML object
        wp_html = weasyprint.HTML(string=full_html)

        # Additional print CSS
        print_css = CSS(string=self._get_print_css())

        # Render to PDF
        pdf_bytes = wp_html.write_pdf(stylesheets=[print_css])

        log.info(
            "pdf_renderer.rendered",
            extra={"title": title, "size_kb": len(pdf_bytes) // 1024},
        )

        return pdf_bytes

    def render_to_file(
        self,
        html_content: str,
        output_path: str,
        title: str = "SpiderFoot Report",
    ) -> str:
        """Render HTML to PDF file on disk.

        Returns:
            The output file path.
        """
        pdf_bytes = self.render(html_content, title)
        os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
        with open(output_path, "wb") as f:
            f.write(pdf_bytes)
        return output_path

    def render_to_stream(
        self,
        html_content: str,
        title: str = "SpiderFoot Report",
    ) -> io.BytesIO:
        """Render HTML to an in-memory BytesIO stream."""
        pdf_bytes = self.render(html_content, title)
        stream = io.BytesIO(pdf_bytes)
        stream.seek(0)
        return stream

    # -----------------------------------------------------------------
    # Private helpers
    # -----------------------------------------------------------------

    def _build_full_document(self, body_html: str, title: str) -> str:
        """Wrap body HTML in a full document with cover page and styles."""
        branding = self.config.branding

        cover_page = ""
        if self.config.include_cover_page:
            logo_html = ""
            if branding.logo_path and os.path.isfile(branding.logo_path):
                logo_html = f'<img src="file://{branding.logo_path}" class="cover-logo" alt="Logo">'

            cover_page = f"""
            <div class="cover-page">
                {logo_html}
                <h1 class="cover-title">{title}</h1>
                <p class="cover-subtitle">{branding.cover_subtitle}</p>
                <p class="cover-company">{branding.company_name}</p>
                <p class="cover-date" id="cover-date"></p>
            </div>
            """

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{title}</title>
    <style>
        {self._get_base_css()}
    </style>
</head>
<body>
    {cover_page}
    <div class="report-content">
        {body_html}
    </div>
</body>
</html>"""

    def _get_base_css(self) -> str:
        """Base CSS for the PDF document."""
        b = self.config.branding
        return f"""
        /* ---- Reset ---- */
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}

        body {{
            font-family: {b.font_family};
            font-size: 10pt;
            line-height: 1.6;
            color: #1a1a2e;
        }}

        /* ---- Cover page ---- */
        .cover-page {{
            page-break-after: always;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            text-align: center;
            padding: 40mm 20mm;
        }}

        .cover-logo {{
            max-width: 200px;
            max-height: 80px;
            margin-bottom: 40px;
        }}

        .cover-title {{
            font-size: 28pt;
            font-weight: 700;
            color: {b.primary_color};
            margin-bottom: 10px;
            line-height: 1.2;
        }}

        .cover-subtitle {{
            font-size: 14pt;
            color: #555;
            margin-bottom: 30px;
        }}

        .cover-company {{
            font-size: 12pt;
            color: {b.secondary_color};
            font-weight: 600;
        }}

        .cover-date {{
            font-size: 10pt;
            color: #888;
            margin-top: 20px;
        }}

        /* ---- Report body ---- */
        .report-content {{
            max-width: 100%;
        }}

        h1 {{
            font-size: 20pt;
            color: {b.primary_color};
            border-bottom: 2px solid {b.primary_color};
            padding-bottom: 6px;
            margin: 20px 0 10px 0;
            page-break-after: avoid;
        }}

        h2 {{
            font-size: 14pt;
            color: {b.primary_color};
            margin: 16px 0 8px 0;
            page-break-after: avoid;
        }}

        h3 {{
            font-size: 12pt;
            color: #333;
            margin: 12px 0 6px 0;
            page-break-after: avoid;
        }}

        p {{
            margin-bottom: 8px;
            text-align: justify;
        }}

        /* ---- Tables ---- */
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 10px 0;
            font-size: 9pt;
            page-break-inside: auto;
        }}

        thead {{
            background-color: {b.primary_color};
            color: white;
        }}

        th, td {{
            border: 1px solid #ddd;
            padding: 6px 8px;
            text-align: left;
        }}

        tr:nth-child(even) {{
            background-color: #f8f9fa;
        }}

        tr {{
            page-break-inside: avoid;
        }}

        /* ---- Code blocks ---- */
        code {{
            font-family: 'JetBrains Mono', 'Fira Code', monospace;
            font-size: 8.5pt;
            background: #f5f5f5;
            padding: 1px 4px;
            border-radius: 3px;
        }}

        pre {{
            background: #f5f5f5;
            padding: 10px;
            border-radius: 4px;
            font-size: 8pt;
            overflow-wrap: break-word;
            white-space: pre-wrap;
            page-break-inside: avoid;
        }}

        /* ---- Severity badges ---- */
        .severity-critical {{
            background: #d32f2f;
            color: white;
            padding: 2px 8px;
            border-radius: 3px;
            font-size: 8pt;
            font-weight: 600;
        }}
        .severity-high {{
            background: #f57c00;
            color: white;
            padding: 2px 8px;
            border-radius: 3px;
            font-size: 8pt;
            font-weight: 600;
        }}
        .severity-medium {{
            background: #fbc02d;
            color: #333;
            padding: 2px 8px;
            border-radius: 3px;
            font-size: 8pt;
        }}
        .severity-low {{
            background: #4caf50;
            color: white;
            padding: 2px 8px;
            border-radius: 3px;
            font-size: 8pt;
        }}
        .severity-info {{
            background: #2196f3;
            color: white;
            padding: 2px 8px;
            border-radius: 3px;
            font-size: 8pt;
        }}

        /* ---- Lists ---- */
        ul, ol {{
            margin: 6px 0 6px 20px;
        }}

        li {{
            margin-bottom: 3px;
        }}
        """

    def _get_print_css(self) -> str:
        """Additional @page rules for print output."""
        b = self.config.branding
        cfg = self.config

        footer_content = ""
        if cfg.include_header_footer:
            footer_content = f"""
            @bottom-center {{
                content: "{b.footer_text}";
                font-size: 7pt;
                color: #888;
            }}
            """

        page_number = ""
        if cfg.include_page_numbers:
            page_number = """
            @bottom-right {
                content: "Page " counter(page) " of " counter(pages);
                font-size: 7pt;
                color: #888;
            }
            """

        return f"""
        @page {{
            size: {cfg.page_size} {cfg.orientation};
            margin-top: {cfg.margin_top};
            margin-bottom: {cfg.margin_bottom};
            margin-left: {cfg.margin_left};
            margin-right: {cfg.margin_right};

            {footer_content}
            {page_number}
        }}

        @page :first {{
            margin: 0;
            @bottom-center {{ content: none; }}
            @bottom-right {{ content: none; }}
        }}
        """
