name: Docker Image CI

on:
  push:
    branches: [master, "*-dev"]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Lint Dockerfile with Hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        failure-threshold: error 
        
    - name: Login to GitHub Container Registry (if needed)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:v5.0.4-dev
          ghcr.io/${{ github.repository }}:${{ github.sha }}
    - name: Trivy vulnerability scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/${{ github.repository }}:${{ github.sha }}'
        ignore-unfixed: 'true'
          
    - name: Run container tests
      run: |
        docker run --rm ghcr.io/${{ github.repository }}:${{ github.sha }} sf.py -h
        docker run --rm ghcr.io/${{ github.repository }}:${{ github.sha }} sf.py --version

    - name: Start SpiderFoot container
      run: |
        timeout 60 docker run -d -p 5001:5001 -p 8000:8000 ghcr.io/poppopjmp/spiderfoot:${{ github.sha }}

    - name: Wait for SpiderFoot to start
      run: |
        timeout 60 bash -c 'until curl --output /dev/null --silent --head --fail http://127.0.0.1:5001/test; do printf "."; sleep 1; done'
        echo "SpiderFoot is up!"

